name: Deployment
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Load and cache dependencies
        uses: ./.github/actions/cache_deps

      - name: Test code
        id: tests
        run: npm run test

      - name: Upload test report
        if: failure() && steps.tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json