name: Website Deployment
on:
    push:
        branches:
            -master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get application code
              uses: actions/checkout@v4

            # - name: Cache dependencies

            #   uses: 

            - name: Install dependencies
              run: npm ci

            
